name: ☢️ Danger - Yarn

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-danger-yarn:
    uses: artsy/duchamp/.github/workflows/danger-yarn.yml@fix-fail-danger
    secrets:
      danger-token: ${{ secrets.DANGER_TOKEN }}
